name: Publish to Github Packages
on:
  push:
    branches: [ dev-nesk ]
jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Add Github Packages to NuGet sources
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ github.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
      - name: Pack OVRSharp
        run: dotnet pack -c Release -o dist --version-suffix dev-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short ${{ github.sha }})

      - name: Publish to NuGet
        run: dotnet nuget push dist/* --api-key ${{ github.token }} --source github
